nome=input("Digite um funcionário: ")
empresa=input("Digite o nome da Instituição: ")
qtdade_funcionarios=int(input("Digite a quantidade de funcionários: "))
mediaSalarial=float(input("Digite a média salarial: "))
print(nome+" trabalha na empresa "+empresa)
print("A empresa possui ", qtdade_funcionarios,"funcionários.")
print("A média salarial é R$",mediaSalarial)
print("O tipo de dado da variável [nome] é: ", type(nome))
print("O tipo de dado da variável [empresa] é: ", type(empresa))
print("O tipo de dado da variável [qtdade_funcionarios] é: ", type(qtdade_funcionarios))
print("O tipo de dado da variável [mediaSalarial] é: ", type(mediaSalarial))